### ISSUE TITLE
Definition about 'ingoing' and 'outgoing'

### ISSUE THREAD

**Issue by CiaoHe** [lucidrains/triangle-multiplicative-module#1]
Hi Luci!

I've seen the lines define the 'ingoing' and 'outgoing':
`if mix == 'ingoing':
    self.mix_einsum_eq = '... i k d, ... j k d -> ... i j d'
elif mix == 'outgoing':
    self.mix_einsum_eq = '... k j d, ... k i d -> ... i j d'`

but based on the original paper, I found maybe should be the inverse case, that:
`if mix == 'ingoing':
    self.mix_einsum_eq = '... k i d, ... k j d -> ... i j d'
elif mix == 'outgoing':
    self.mix_einsum_eq = '... j k d, ... i k d -> ... i j d'`

based on what I understand, 'ingoing' should be the case that information comes from other edges (like 'ki','kj') aggregate togther and bind with edge 'ij'. 

Thanks for your contribution!

**Comment by lucidrains** [comment]
@CiaoHe Hi HeCao! Thanks for reviewing the repository, and you indeed caught yet another bug! https://github.com/lucidrains/triangle-multiplicative-module/commit/0b019e081daf13bc6f8513cb7084dff644322957 Should be fixed 🙏
